import { FormField } from "@/hooks/types";

export const BillingFormType: FormField[] = [
  {
    name: "billNumber",
    type: "text",
    required: true,
    label: "Bill Number",
    placeholder: "Enter Bill Number",
  },
  {
    name: "billDate",
    type: "date",
    required: true,
    label: "Bill Date",
    placeholder: "Select Bill Date",
    isDisabled: false,
  },
  {
    name: "invoiceTo",
    type: "select",
    required: true,
    label: "Invoice To",
    placeholder: "Select Invoice To",
    isDisabled: false,
    options: [],
  },
  {
    name: "referenceNo",
    type: "text",
    required: true,
    label: "Reference No.",
    placeholder: "Enter Reference No.",
    isDisabled: false,
  },
  {
    name: "shipTo",
    type: "select",
    required: true,
    label: "Ship To",
    placeholder: "Select Ship To",
    isDisabled: true,
    options: [],
  },

  {
    name: "vehicleDetails",
    type: "text",
    required: false,
    label: "Vehicle Dtl.",
    placeholder: "Enter Vehicle Details",
    isDisabled: false,
  },
  {
    name: "driverName",
    type: "text",
    required: false,
    label: "Driver Dtl.",
    placeholder: "Enter Driver Details",
    isDisabled: false,
  },
  {
    name: "dispatchMode",
    type: "select",
    required: false,
    label: "Dispatch Mode",
    placeholder: "Select Dispatch Mode",
    isDisabled: false,
    options: [],
  },
  {
    name: "preparedBy",
    type: "text",
    required: false,
    label: "Prepare By",
    placeholder: "Enter Name",
    isDisabled: false,
  },
  {
    name: "placeOfSupply",
    type: "text",
    required: false,
    label: "Place of Supply",
    placeholder: "Enter Place of Supply",
    isDisabled: false,
  },
  {
    name: "transportThrough",
    type: "text",
    required: false,
    label: "Transport Through",
    placeholder: "Enter Transport Details",
    isDisabled: false,
  },
  {
    name: "grLrNo",
    type: "text",
    required: false,
    label: "GR/LR No",
    placeholder: "Enter GR/LR Number",
    isDisabled: false,
  },

  {
    name: "remarks",
    type: "textarea",
    required: false,
    label: "Remarks",
    placeholder: "Enter Remarks",
    isDisabled: false,
  },
];
