import { FormField } from "@/hooks/types";
import { formatDate } from "@/hooks/general";
import { includes } from "@/hooks/polyfills";

export const LeadFormType: FormField[] = [
  {
    name: "name",
    type: "text",
    required: true,
    label: "User Name",
    placeholder: "Enter user name",
  },
  {
    name: "mobileNo",
    maxLength: 15,
    label: "Mobile Number",
    type: "stringNumeric",
    placeholder: "Enter your mobile number",
    required: true,
  },
  {
    name: "altMobileNo",
    maxLength: 15,
    label: "Alternate Mobile Number",
    type: "stringNumeric",
    placeholder: "Enter your alternate mobile number",
  },
  {
    name: "email",
    type: "email",
    label: "Email",
    required: true,
    placeholder: "Enter your email",
    validation: (value) => (includes(value, "@") ? null : "Invalid email"),
  },
  {
    name: "birthDate",
    label: "Date of Birth",
    type: "date",
    required: false,
    maxDate: formatDate(new Date()),
    placeholder: "Enter date of birth",
  },
  {
    name: "joiningDate",
    label: "Joining Date",
    type: "date",
    required: false,
    placeholder: "Enter join date",
  },
  {
    name: "leavingDate",
    label: "Leaving Date",
    type: "date",
    required: false,
    placeholder: "Enter date of leaving",
  },
  {
    type: "text",
    name: "qualification",
    label: "User's Qualification",
    placeholder: "Enter user's Qualification",
  },
  {
    name: "panNo",
    type: "text",
    label: "User's PAN Number",
    placeholder: "Enter user's PAN Number",
  },
  {
    name: "aadhaarNo",
    type: "text",
    label: "User's Aadhar Number",
    placeholder: "Enter user's Aadhar Number",
  },
  {
    name: "familyRefInfo",
    type: "text",
    label: "User's Family Reference Information",
    placeholder: "Enter user's Family Reference Information",
  },
  {
    name: "basic",
    maxLength: 10,
    type: "number",
    label: "Basic Salary",
    placeholder: "Enter basic Salary",
  },
  {
    name: "hra",
    maxLength: 10,
    type: "number",
    label: "Home Rental Allowance",
    placeholder: "Enter Home Rental Allowance",
  },
  {
    name: "conveyance",
    maxLength: 10,
    type: "number",
    label: "Conveyance",
    placeholder: "Enter conveyance",
  },
  {
    name: "status",
    label: "Do you want to activate this user?",
    type: "choose",
    required: false,
  },
  {
    name: "line1",
    type: "text",
    required: true,
    label: "Address Line 1",
    placeholder: "Enter address line 1",
  },
  {
    name: "street",
    type: "text",
    label: "Street Name",
    placeholder: "Enter street name",
  },
  {
    name: "landmark",
    type: "text",
    label: "Landmark",
    placeholder: "Enter landmark",
  },
  {
    name: "country",
    type: "text",
    required: true,
    label: "Country",
    placeholder: "Enter country",
  },
  {
    name: "state",
    type: "text",
    required: true,
    label: "State",
    placeholder: "Enter state",
  },
  {
    name: "city",
    type: "text",
    required: true,
    label: "City",
    placeholder: "Enter city",
  },
  {
    name: "pinCode",
    type: "text",
    required: true,
    label: "Pincode",
    placeholder: "Enter pincode",
  },
  {
    name: "latitude",
    type: "text",
    label: "Latitude",
    placeholder: "Enter latitude",
  },
  {
    name: "longitude",
    type: "text",
    label: "Longitude",
    placeholder: "Enter longitude",
  },
  {
    name: "profilePic",
    label: "Profile Image",
    type: "file",
    required: true,
  },
  {
    name: "panCardDoc",
    label: "Pan Card Image",
    type: "file",
  },
  {
    name: "aadhaarCardDoc",
    label: "Aadhar Card Image",
    type: "file",
  },
  {
    name: "otherDoc",
    label: "Other Documents Image",
    type: "file",
  },
];
