import { FormField } from "@/hooks/types";

export const ReceivingFormType: FormField[] = [
  {
    type: "select",
    required: true,
    name: "receivingType",
    label: "Receiving Type",
    placeholder: "Select type",
    options: [
      { label: "Invoice", value: "Invoice" },
      { label: "Purchase Return", value: "Purchase Return" },
    ],
  },
  {
    name: "ledgerId",
    type: "select",
    required: true,
    label: "Customer / Supplier",
    placeholder: "Select Customer / Supplier",
    options: [], // This will hold the options for the Select component
  },
  {
    type: "select",
    required: true,
    name: "invoiceId",
    label: "Invoice ID",
    placeholder: "Select invoice",
    options: [],
  },
  {
    name: "amount",
    maxLength: 10,
    type: "number",
    required: true,
    label: "Amount",
    placeholder: "Enter amount",
  },
  // {
  //   name: "deduction",
  //   maxLength: 10,
  //   type: "number",
  //   label: "Deduction",
  //   placeholder: "Enter deduction",
  // },
  // {
  //   name: "tdsAmount",
  //   maxLength: 10,
  //   type: "number",
  //   label: "TDS Amount",
  //   placeholder: "Enter TDS Amount",
  // },
  // {
  //   name: "netAmount",
  //   maxLength: 10,
  //   type: "number",
  //   label: "Net Amount",
  //   placeholder: "Enter net Amount",
  // },
  {
    name: "paymentMethod",
    type: "select",
    required: true,
    label: "Payment Method",
    placeholder: "Select method",
    options: [
      { label: "Cash", value: "Cash" },
      { label: "Debit Card", value: "Debit Card" },
      { label: "Credit Card", value: "Credit Card" },
      { label: "Bank Transfer", value: "Bank Transfer" },
      { label: "Online Payment", value: "Online Payment" },
    ],
  },
  {
    name: "paymentDirection",
    type: "select",
    required: true,
    label: "Payment Direction",
    placeholder: "Select direction",
    options: [{ label: "Received", value: "Received" }],
  },
  {
    name: "paymentStatus",
    type: "select",
    required: true,
    label: "Payment status",
    placeholder: "Select status",
    options: [
      { label: "Failed", value: "Failed" },
      { label: "Pending", value: "Pending" },
      { label: "Completed", value: "Completed" },
    ],
  },
  {
    rows: 1,
    type: "text",
    name: "remarks",
    required: true,
    label: "Remarks",
    placeholder: "Enter remarks",
  },
];
